"""Add description to rooms

Revision ID: 20250501_add_description
Revises: 4dba0ce02cf0
Create Date: 2025-05-01 05:52:18.227127

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20250501_add_description'
down_revision = '4dba0ce02cf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('description', sa.Text(), nullable=True))
    
    # Add updated_at column if it doesn't exist
    op.add_column('rooms', sa.Column('updated_at', sa.DateTime(), nullable=True))
    
    # Create a trigger for PostgreSQL to auto-update updated_at
    op.execute("""
        CREATE OR REPLACE FUNCTION update_updated_at_column()
        RETURNS TRIGGER AS $$
        BEGIN
            NEW.updated_at = NOW();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)
    
    op.execute("""
        CREATE TRIGGER update_rooms_updated_at
        BEFORE UPDATE ON rooms
        FOR EACH ROW
        EXECUTE FUNCTION update_updated_at_column();
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove trigger first
    op.execute("DROP TRIGGER IF EXISTS update_rooms_updated_at ON rooms")
    op.execute("DROP FUNCTION IF EXISTS update_updated_at_column()")
    
    # Remove columns
    op.drop_column('rooms', 'updated_at')
    op.drop_column('rooms', 'description')
    # ### end Alembic commands ###