"""Add username to messages

Revision ID: ef600646ec9d
Revises: 4bf2f35d5f5a
Create Date: 2025-04-28 07:37:43.938373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef600646ec9d'
down_revision: Union[str, None] = '4bf2f35d5f5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bets', sa.Column('description', sa.String(), nullable=False))
    op.drop_index('idx_bets_room_id', table_name='bets')
    op.drop_column('bets', 'option')
    op.drop_column('bets', 'amount')
    op.alter_column('messages', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('messages', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index('idx_messages_room_id', table_name='messages')
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.drop_constraint('refresh_tokens_token_key', 'refresh_tokens', type_='unique')
    op.alter_column('users', 'coins',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'coins',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint('refresh_tokens_token_key', 'refresh_tokens', ['token'])
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.create_index('idx_messages_room_id', 'messages', ['room_id'], unique=False)
    op.alter_column('messages', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('messages', 'content',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=False)
    op.alter_column('messages', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('messages', 'room_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('bets', sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('bets', sa.Column('option', postgresql.ENUM('OPTION1', 'OPTION2', name='betoption'), autoincrement=False, nullable=False))
    op.create_index('idx_bets_room_id', 'bets', ['room_id'], unique=False)
    op.drop_column('bets', 'description')
    # ### end Alembic commands ###
